name: Gradle Build CI

on:
  push:
    paths:
      - '**.kt'
      - '**.kts'
      - '**.properties'
  pull_request:
    paths:
      - '**.kt'
      - '**.kts'
      - '**.properties'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - run: chmod +x gradlew && ./gradlew build
        working-directory: .
